version: '3'

tasks:
  install:
    cmds:
      - poetry install --no-root

  lint:
    cmds:
      - ruff hc_pynomad

  lint-ci:
    cmds:
      - task: install
      - task: lint

  test:
    cmds:
      - pytest tests/

  test-ci:
    cmds:
      - task: install
      - task: test
