name: PRs

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
        poetry-version: [1.4.2]
        os: [fedora-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install go-task
        run: |
          dnf install -y go-task
      - name: Lint with flake8/pylint
        run: |
          task lint-ci
      - name: Test with pytest
        run: |
          task test-ci
