name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          python_version: "3.10"
          ignore_dev_requirements: "yes"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
